language: rust

cache: cargo # Cache dependencies so they are only recompiled if they or the compiler were upgraded

_DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - name="mme-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/mme $name/
    - tar czvf $name.tar.gz $name #Use the following command to compress an entire directory or a single file on Linux
  deploy:
    edge: true
    provider: releases
    file: mme-$TRAVIS_TAG-$TARGET.tar.gz
    cleanup: true #skip_cleanup set to true, otherwise Travis will delete all the files created during the build
    on:
      branch: master
      tags: true
    token: "kJ/Fq/n9QAapqdfwNFQ+UeeqHf9UDn2WB+q0QyGRLeCq+ixPBYrTexk2voR4trfVwO5Ptr3niJmm90PePsPDASsuq4jiWqX2xG0eutcfONgqCEdTlgdMfgWluGBz5kHeTkvS2IMH2CNA/WdaG7mDmbUrgCsnLHRPgjfnMdWpS9es7fTXu+OSsNtFRHLAoE2QRCas1xRdpqTRCT5CE0S847aO0shURa9PKmZDwsVyIV1zBZNUWPie8VC76zx0cVW/u/zoi7qjDg6anCvPIrk1qqRDwMFXNEsUi00u7EiEQtanBYgou893y192AP191HHWFB4/hRECaZNGVcg7MWQNgquaLMaw/U1srkzmMPuTXjXiPuOu4K5mW6UtZ0LMA05hD+wEyNAt38AUXA+Hr8Mzr3DxGcXeSHLtTBiykHWiyFMQ2b57YWByBx5WTlFkh127AZ8eVwjIgEw38B99XT8Io4cDwRpjXj5NRmUHtPn20bRAZ2G64J59aRyMkr47bGrGBRuNUIBwU372CzOJRfPio3SZAfxTel5LblJyMO9vnF8SIoI280vApkwL+9bfbIwxCf+dwLKcJ5XhZ8fEaF7f2rOyUNxzK/BJBHmSSoL1pgVYtijEV2e779LMy61hmhPcZQcc9/GD9E9dmRwxrJMSE78s4BdvQv2gk2EK5vvfGew="

matrix: # Use of a matrix generates copies of a job, each with different input
  include:
    - name: Linux Binary
      env: TARGET=x86_64-unknown-linux-musl
      rust: beta
      script:
        - rustup target add x86_64-unknown-linux-musl
        - cargo build --release --target $TARGET
      <<: *DEPLOY_TO_GITHUB

    - name: macOS Binary
      env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
      os: osx
      rust: beta
      script: cargo build --release --target $TARGET
      <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never
