language: rust
cache: cargo
_DEPLOY_TO_GITHUB:
  before_deploy: &1
    - name="mme-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/mme $name/
    - tar czvf $name.tar.gz $name
  deploy: &2
    edge: true
    provider: releases
    file: mme-$TRAVIS_TAG-$TARGET.tar.gz
    cleanup: true
    on:
      branch: master
      tags: true
matrix:
  include:
    - name: Linux Binary
      env: TARGET=x86_64-unknown-linux-musl
      rust: beta
      script:
        - rustup target add x86_64-unknown-linux-musl
        - cargo build --release --target $TARGET
      before_deploy: *1
      deploy: *2
    - name: macOS Binary
      env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
      os: osx
      rust: beta
      script: cargo build --release --target $TARGET
      before_deploy: *1
      deploy: *2
notifications:
  email:
    on_success: never
token:
  secure: EGdHzO0j89/beuFbH/IFsUuOj8jEn0z5E1GFHnl7HDHiWiI5v3lXXOfhuYM5c2DfZHuDFtHmuBy+A7MsUSmcV8t2xxic58Jzg31yMkBKjKorDhzQo5VtDe1IhAvJQm7Vtd4N0GKNFu2uslAbmv9m7rU4/JyDPL4AppF3/3l2h8Vc8+J9fh2TC6HLR2Knd0yZSElqTT/0rcj0Uqo8Q+7NYFYEm9ZMQoHLCeX4GUQPnFxyhQZVy18EFZ8vuEtsUJztVdYOAcbaiUbghkQoq8XG3T9+8wriSTICzq4KFNKjHJHnDbSIgSA8gO+pDAV8fMvDg1YOcbTnpwB3MyjXhiQCBgJghDt6qk3ZnQnVKt2T2E7M5hVoWUqtJtxKHSUiz9vH/U/wShoqLbJOwF9calgQAmokwbduZQwMeTU19HvxwgPNUAwT+RVzXfK4d0dBjjk4lXlWJn/YLNJmC5iRPJ/EOZB7c31tcSNjGciowl1N614SUb7VRovYx4qwtNuJAo35vL2kdS+ntGgP52N73Omr0KHj4D1dHiIXHZzDc8MACCHTSDMtRTifHOF4MaY8cNcLkd/xXgv+I4K8Df6odWXt6XbSmOcgE6Kf19B85goTzMjRI0OEyxamvMYmJxfsMfVTa6rMqAUaKhk7WQkAWOiJvcZUetfczeRbWtiBkQW4hlk=
