name: Windows-build

on:
  release:
    types: [published]

jobs:
  build:
    # The type of runner that the job will run on
    name: Publish windows binaries
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: geturl
      run: |
        $OutputVariable = (curl -s https://api.github.com/repos/goberinfinity/mme/releases/latest | jq -r '.upload_url')
        echo ::set-env name=production::$OutputVariable
        
    - name: Check outputs
      shell: pwsh
      run: echo ${{ steps.vars.outputs.production }}

    - name: Upload binaries
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.vars.outputs.production }}
          asset_path: target/release/mme.exe
          asset_name: mme-windows-amd64
          asset_content_type: application/x-msdownload
