name: Windows-build

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    name: Publish windows binaries
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Build
      run: cargo build --release
