name: Windows-build

on:
  release:
    types: [published]

jobs:
  build:
    # The type of runner that the job will run on
    name: Publish windows binaries
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Build
      run: cargo build --release
    
    - name: Get Id
      run: |
        echo 'Retrieving the id'
        curl https://api.github.com/repos/goberinfinity/mme/releases/latest
        downloadUrl=$(curl https://api.github.com/repos/goberinfinity/mme/releases/latest | jq '.upload_url' | tr -d '"')
        echo $downloadUrl
        
    - name: Upload binaries
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: $downloadUrl
          asset_path: target/release/mme.exe
          asset_name: mme-windows-amd64
          asset_content_type: application/x-msdownload
