name: Windows-build

on:
  release:
    types: [published]

jobs:
  build:
    # The type of runner that the job will run on
    name: Publish windows binaries
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --release

    - name: geturl
      run: |
        downloadId=$(curl -s https://api.github.com/repos/goberinfinity/mme/releases/latest | jq -r '.id')
        echo "::set-output name=tid::$downloadId"
      shell: bash
      id: tagid
        
    - name: Upload binaries
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: https://uploads.github.com/repos/GoberInfinity/mme/releases/${{ steps.tagid.outputs.tid }}/assets?name=mme-windows-amd64.exe
          asset_path: target/release/mme.exe
          asset_name: mme-windows-amd64.exe
          asset_content_type: application/x-msdownload
